name: Nodecicd
on:
  push:
    branches:
      - main
jobs: 
  build:
    strategy:
      matrix:
        node-version: [ 20.x]
    runs-on: self-hosted
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version  }}
          cache: 'npm'
      - name: install dependencies
        run: npm ci 
      - name: run test
        run: npm test
      - name: restart server
        run: sudo pm2 restart backendserver